debug: false
uuid: 1c6f2fd0-17ef-46dd-bb0b-dac47272f4ce
token_id: f5pc1O6PW0j7aIKA
token: hKZqMbakIqAdCh8S66YyEEqrmVBc5BdqXZRrsWAJG4ynFB7x4wpQl24t0RJZVh7J
api:
  host: 0.0.0.0
  port: 445
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/genuinely-above-cowbird.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/genuinely-above-cowbird.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://89.213.174.227:51521'
