debug: false
uuid: afeaecde-8466-4721-9d63-2396bede317a
token_id: H6axbk3BKSPfVbmr
token: ZcYXzJi0foo9cE58g4EyTOqOJllwOFdNpA15fiWjVrfawJjp53qItqeo9lnjhXGU
api:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/genuinely-above-cowbird.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/genuinely-above-cowbird.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://185.234.69.13:33201'
